Allow options in ensure-table! to pass to table-exists!
techascent/tech.ml.dataset.sql pull request #8
Opened 2022-08-12 23:14 UTC by Jacob-Kroeze

2022-08-13 14:52 UTC, cnuernber requested changes
Just one thing - What version of Clojure are you testing this with?

2022-08-13 14:52 UTC, cnuernber commented on src/tech/v3/dataset/sql.clj
> +    [conn dataset & options]
I think for older versions of Clojure this should be `& [options]` instead of `& options`.  Else it will be a map wrapped in a sequence.

2022-08-13 22:19 UTC, Jacob-Kroeze commented
@cnuernber Oops. Good point. For 1.10 and 1.11 tests pass on the new commit fixing the options param. For 1.9, I get broken tests with 
```
clj -M:dev:1.9:test 

Running tests in #{"test"}
Exception in thread "main" java.lang.RuntimeException: Unable to resolve symbol: requiring-resolve in this context, compiling:(tech/v3/datatype/functional_api.clj:202:6)
```

2022-08-20 21:30 UTC, merged

2022-08-20 21:31 UTC, cnuernber commented
Thanks a lot, I really appreciate the help!